version: '3.1'

services:
  postgres:
    image: postgres
    restart: always
    command: postgres -c 'max_connections=200'
    environment:
      POSTGRES_DB: tucows-challenge
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    volumes:
      - postgres-vol:/var/lib/postgresql/data
    networks:
      - db
    healthcheck:
      test: pg_isready -U postgres
      interval: 5s
      timeout: 5s
      retries: 5

  atlas-migration:
    image: postgres:15.1
    restart: always
    environment:
      POSTGRES_DB: atlas-migration-compare
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: pw1
    ports:
      - "5433:5432"
    networks:
      - db

  sandbox_creator:
    image: accelbyte/pg-sandbox-creator:8ff4a4a6-1698105179
    depends_on:
      - postgres
    volumes:
      - ./db/migrations/:/migrations
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      SANDBOX_CREATOR_PORT: 8081
      ATLAS_CMD: "/atlas"
    ports:
      - "8081:8081"
    networks:
      - db

  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672"
      - "15672:15672"  # Management interface
    volumes:
    - rabbitmq-data:/var/lib/rabbitmq
    - ./init-queues.sh:/opt/init-queues.sh
    command: ["bash", "-c", "/opt/init-queues.sh & rabbitmq-server"]
    networks:
      - db
    restart: always

networks:
  db:

volumes:
  postgres-vol:
  rabbitmq-data:
